### ISSUE TITLE
[request] Switch the media playback library

### ISSUE THREAD

**Issue by alexmercerind** [stonega/tsacdop_desktop#1]
Hi there!

Tsacdop is one of my favorite apps in Flutter.
I see you are using `flutter_audio_desktop` for audio playback, since that library has many big problems in general & performance isn't great either. So, now [dart_vlc](https://github.com/alexmercerind/dart_vlc) is the project that is sequel to it, and contains things like:
- playlists.
- network streaming.
- assets playback.
- prebuilt streams to listen to events.
- better format support.
- better performance.
- metadata retrieving [currently not implemented] 

I'm in contact with ryanheise (maintainer of just_audio, as you are using the same in your mobile version of app) aswell, to get Windows & Linux support using my plugin I mentioned above.

Thanks!

Thought it was my responsibility to inform you. There hasn't been much activity on this repository due to lack of library I see, now things are getting on track to make Flutter great on Windows & Linux.

**Comment by stonega** [comment]
This is a really good progress, I am hasitated to contine to develop desktop version with flutter, because of many plugins is missing,  I switch to use linux last year, I am event considering to learn rust to develop native gtk podcast player for linux,  but t is really a challenge for me.
Your update is so graet, I will have a try to see what I can make with it.

**Comment by stonega** [comment]
I have switched to  new plugin, thanks!
